### ISSUE TITLE
📄 Add MIT License everywhere

### ISSUE THREAD

**Issue by cmg-dev** [essential-projects/meta#1]
What is to do?

Please check in Each PR that

1. the MIT license is set accordingly
1. the package.json contains the `'license': 'MIT'` field

The following Repos have been affected and a PR is open:

- [x] [bootstrapper](https://github.com/essential-projects/bootstrapper/pulls)
- [x] [bootstrapper_browser](https://github.com/essential-projects/bootstrapper_browser/pulls)
- [x] [bootstrapper_node](https://github.com/essential-projects/bootstrapper_node/pulls)
- [x] [caching](https://github.com/essential-projects/caching/pulls)
- [x] [caching_contracts](https://github.com/essential-projects/caching_contracts/pulls)
- [x] [core](https://github.com/essential-projects/core/pulls)
- [x] [core_contracts](https://github.com/essential-projects/core_contracts/pulls)
- [x] [data_model](https://github.com/essential-projects/data_model/pulls)
- [x] [data_model_contracts](https://github.com/essential-projects/data_model_contracts/pulls)
- [x] [datasource_adapter_base](https://github.com/essential-projects/datasource_adapter_base/pulls)
- [x] [datasource_adapter_localstorage](https://github.com/essential-projects/datasource_adapter_localstorage/pulls)
- [x] [datasource_adapter_mongodb](https://github.com/essential-projects/datasource_adapter_mongodb/pulls)
- [x] [datasource_adapter_orientdb](https://github.com/essential-projects/datasource_adapter_orientdb/pulls)
- [x] [datasource_adapter_postgres](https://github.com/essential-projects/datasource_adapter_postgres/pulls)
- [x] [datasource_adapter_proxy](https://github.com/essential-projects/datasource_adapter_proxy/pulls)
- [x] [datasource_adapter_redis](https://github.com/essential-projects/datasource_adapter_redis/pulls)
- [x] [datastore](https://github.com/essential-projects/datastore/pulls)
- [x] [datastore_contracts](https://github.com/essential-projects/datastore_contracts/pulls)
- [x] [datastore_http](https://github.com/essential-projects/datastore_http/pulls)
- [x] [datastore_messagebus](https://github.com/essential-projects/datastore_messagebus/pulls)
- [x] [datastore_messagebus_contracts](https://github.com/essential-projects/datastore_messagebus_contracts/pulls)
- [x] [essential](https://github.com/essential-projects/essential-projects.github.io/pulls)
- [x] [event_aggregator](https://github.com/essential-projects/event_aggregator/pulls)
- [x] [event_aggregator_contracts](https://github.com/essential-projects/event_aggregator_contracts/pulls)
- [x] [feature](https://github.com/essential-projects/feature/pulls)
- [x] [feature_contracts](https://github.com/essential-projects/feature_contracts/pulls)
- [x] [foundation](https://github.com/essential-projects/foundation/pulls)
- [x] [graphql](https://github.com/essential-projects/graphql/pulls)
- [x] [graphql_contracts](https://github.com/essential-projects/graphql_contracts/pulls)
- [x] [graphql_http](https://github.com/essential-projects/graphql_http/pulls)
- [x] [http](https://github.com/essential-projects/http/pulls)
- [x] [http_contracts](https://github.com/essential-projects/http_contracts/pulls)
- [x] [http_extension](https://github.com/essential-projects/http_extension/pulls)
- [x] [http_node](https://github.com/essential-projects/http_node/pulls)
- [x] [iam](https://github.com/essential-projects/iam/pulls)
- [x] [iam_browser](https://github.com/essential-projects/iam_browser/pulls)
- [x] [iam_contracts](https://github.com/essential-projects/iam_contracts/pulls)
- [x] [iam_http](https://github.com/essential-projects/iam_http/pulls)
- [x] [invocation](https://github.com/essential-projects/invocation/pulls)
- [x] [invocation_contracts](https://github.com/essential-projects/invocation_contracts/pulls)
- [x] [messagebus](https://github.com/essential-projects/messagebus/pulls)
- [x] [messagebus_adapter_faye](https://github.com/essential-projects/messagebus_adapter_faye/pulls)
- [x] [messagebus_adapter_faye_browser](https://github.com/essential-projects/messagebus_adapter_faye_browser/pulls)
- [x] [messagebus_adapter_local](https://github.com/essential-projects/messagebus_adapter_local/pulls)
- [x] [messagebus_contracts](https://github.com/essential-projects/messagebus_contracts/pulls)
- [x] [messagebus_http](https://github.com/essential-projects/messagebus_http/pulls)
- [x] [metadata](https://github.com/essential-projects/metadata/pulls)
- [x] [metadata_contracts](https://github.com/essential-projects/metadata_contracts/pulls)
- [x] [pki_service](https://github.com/essential-projects/pki_service/pulls)
- [x] [pki_service_contracts](https://github.com/essential-projects/pki_service_contracts/pulls)
- [x] [routing](https://github.com/essential-projects/routing/pulls)
- [x] [routing_contracts](https://github.com/essential-projects/routing_contracts/pulls)
- [x] [security_service](https://github.com/essential-projects/security_service/pulls)
- [x] [security_service_contracts](https://github.com/essential-projects/security_service_contracts/pulls)
- [x] [services](https://github.com/essential-projects/services/pulls)
- [x] [services_contracts](https://github.com/essential-projects/services_contracts/pulls)
- [x] [timing](https://github.com/essential-projects/timing/pulls)
- [x] [timing_contracts](https://github.com/essential-projects/timing_contracts/pulls)
- [x] [tslint](https://github.com/essential-projects/tslint-config/pulls)
- [x] [validation](https://github.com/essential-projects/validation/pulls)
- [x] [validation_contracts](https://github.com/essential-projects/validation_contracts/pulls)

**Comment by cmg-dev** [comment]
@heikomat ich würde das mergen und meta dafür benutzen.

Bitte einfach nur approven.

**Comment by cmg-dev** [comment]
@alexanderkasten @SteffenKn @MiguelACarballo 

Please divide those Repos into three parts of work; check everything; only approve the PR!

I will merge this in the morning, together with you guys.

Thanks.

**Comment by alexanderkasten** [comment]
👍
